theme: jekyll-theme-cayman
title: CHAD - Controlled Highly Accurate Deadeye
description: A robot that plays beer pong, built by Akash Gokul, Artun Dalyan, Mina Beshay, and George Wang

github:
  repository_url: https://github.com/chad-bot/CHADBot
